name: Functional Android App Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  android-app:

    # No hardware acceleration is available for emulators on Ubuntu:
    # https://github.com/marketplace/actions/android-emulator-runner#can-i-use-this-action-on-linux-vms
    runs-on: macos-latest
    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
            node-version-file: '.nvmrc'

      - name: 🧩 Install Dependencies
        run: |
          npm ci

      - name: 📦 Download app
        run: |
            mkdir apps
            wget https://github.com/webdriverio/native-demo-app/releases/download/v1.0.8/android.wdio.native.app.v1.0.8.apk -P apps

      - name: 📬 Upload App to Sauce Labs
        run: |
          SAUCE_USERNAME=$SAUCE_USERNAME
          SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY
          APP_FILE_PATH=$(pwd)/apps/android.wdio.native.app.v1.0.8.apk

          response=$(curl -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location \
          --request POST 'https://api.eu-central-1.saucelabs.com/v1/storage/upload' \
          --form "payload=@$APP_FILE_PATH" \
          --form 'name="wdio-demo-app-android.apk"' \
          --form 'description="Android WDIO Demo App"')

          # Extract the file ID from the response
          file_id=$(echo "$response" | jq -r '.item.id')

          # Print the file_id value
          echo "File ID to be deleted: $file_id"

      - name: 📲 Run Tests on Android Emulator
        run: npm run android.sauce.emulators.app.eu

      - name: 💾 Save server output
        if: failure()
        uses: actions/upload-artifact@v4
        with:
            name: android-runner-output
            path: |
                logs/
