name: Functional Android App Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  android-app:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
            node-version-file: '.nvmrc'

      - name: 🧩 Install Dependencies
        run: |
          npm ci

      - name: 📦 Download app
        run: |
            mkdir -p apps
            wget https://github.com/webdriverio/native-demo-app/releases/download/v1.0.8/android.wdio.native.app.v1.0.8.apk -P apps

      - name: 📬 Upload App to Sauce Labs
        run: |
            curl -v \
                -F "payload=@./apps/android.wdio.native.app.v1.0.8.apk" \
                -F name=wdio-demo-app-android.apk \
                -u "${{ secrets.SAUCE_USERNAME }}:${{ secrets.SAUCE_ACCESS_KEY }}" \
                'https://api.eu-central-1.saucelabs.com/v1/storage/upload'

      - name: 📲 Run Tests on an Android Emulator
        run: npm run android.sauce.emulators.app.eu

    # Not needed now we are running on Sauce Labs
    #   - name: 💾 Save server output
    #     if: failure()
    #     uses: actions/upload-artifact@v4
    #     with:
    #         name: android-runner-output
    #         path: |
    #             logs/
