name: Functional Android App Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  android-app:

    # No hardware acceleration is available for emulators on Ubuntu:
    # https://github.com/marketplace/actions/android-emulator-runner#can-i-use-this-action-on-linux-vms
    runs-on: macos-latest
    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
            node-version-file: '.nvmrc'

      - name: 🧩 Install Dependencies
        run: npm ci

      - name: 📦 Download app
        run: |
            mkdir apps
            wget https://github.com/webdriverio/native-demo-app/releases/download/v1.0.8/android.wdio.native.app.v1.0.8.apk -P apps

      - name: ☕ Setup Java and Android SDK
        uses: actions/setup-java@v4
        with:
            java-version: '11'
            distribution: 'temurin'

        # Using cache due to ANR issues
        # https://github.com/ReactiveCircus/android-emulator-runner/issues/129
      - name: 🧳 Cache AVD snapshot
        uses: actions/cache@v3
        id: avd-cache
        with:
            path: |
                ~/.android/avd/*
                ~/.android/adb*
            key: avd-30-aosp-atd

        # https://github.com/marketplace/actions/android-emulator-runner#configurations
      - name: 📱 Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
            # Use the slimmer aosp_atd images for working
            # around "System UI isn't responding" ANR
            # (Application Not Responding) error
            #
            # https://android-developers.googleblog.com/2021/10/whats-new-in-scalable-automated-testing.html#:~:text=Slimmer%20Emulator%20System%20Images
            # https://github.com/ReactiveCircus/android-emulator-runner/issues/129
            # https://github.com/upleveled/hotline-bling-codealong/pull/26#issuecomment-1094659722
            target: aosp_atd
            api-level: 30
            arch: x86_64
            channel: canary
            profile: pixel
            avd-name: gha_pixel
            cores: 4
            force-avd-creation: false
            emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
            disable-animations: false
            script: echo "Generated AVD snapshot for caching"

      - name: 📲 Start Android Emulator and Run Tests on Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
            target: aosp_atd
            api-level: 30
            arch: x86_64
            channel: canary
            profile: pixel
            avd-name: gha_pixel
            cores: 4
            script: npm run android.app

      - name: 💾 Save server output
        if: failure()
        uses: actions/upload-artifact@v4
        with:
            name: android-runner-output
            path: |
                logs/
