name: Functional Android App Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  android-app:

    # No hardware acceleration is available for emulators on Ubuntu:
    # https://github.com/marketplace/actions/android-emulator-runner#can-i-use-this-action-on-linux-vms
    runs-on: macos-latest
    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
            node-version-file: '.nvmrc'

      - name: 🧩 Install Dependencies
        run: npm ci

      - name: 📦 Download apps
        run: |
            mkdir apps
            wget https://github.com/webdriverio/native-demo-app/releases/download/v1.0.8/android.wdio.native.app.v1.0.8.apk -P apps

      - name: ☕ Setup Java and Android SDK
        uses: actions/setup-java@v4
        with:
            distribution: 'zulu'
            java-version: '17.x'

        # https://github.com/marketplace/actions/android-emulator-runner#configurations
      - name: 📱 Setup Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
            avd-name: Pixel_7_Pro_Android_14_API_34
            api-level: 34
            script: yarn android.app

      - name: 📲 Run Tests on Android Emulator
        run: npm run android.app

      - name: Save server output
        if: ${{ always() }}
        uses: actions/upload-artifact@master
        with:
            name: appium-api
            path: appium.log
